services:
  db:
    image: postgres
    restart: always
    container_name: as3_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d/"
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=matthias@forensx.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PDADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    depends_on:
      - "db"
    logging:
      driver: none
    networks:
      - db_network
    tty: true

  rapidsai:
    ulimits:
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - '8888:8888'
      - '8787:8787'
      - '8786:8786'
    volumes:
      - '../../../.././:/rapids/notebooks/host/Fall22'
    image: 'rapidsai/rapidsai:22.10-cuda11.5-runtime-ubuntu20.04-py3.8'
    networks:
      - db_network

networks: 
  db_network:
    driver: bridge